services:
  api:
    image: 'contas-a-pagar-api'
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app-network

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=contas-a-pagar'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    networks:
      - app-network

  pgadmin-docker:
    image: 'dpage/pgadmin4'
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@postgres.com"
      PGADMIN_DEFAULT_PASSWORD: 'postgres'
      PGADMIN_LISTEN_PORT: '8001'
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge