CREATE TABLE conta
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_vencimento date,
    data_pagamento  date,
    valor           DECIMAL,
    descricao       VARCHAR(255),
    situacao        SMALLINT,
    CONSTRAINT pk_conta PRIMARY KEY (id)
);

CREATE TABLE usuario
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login VARCHAR(255),
    senha VARCHAR(255),
    CONSTRAINT pk_usuario PRIMARY KEY (id)
);